### ISSUE TITLE
No Index::remove_ids method

### ISSUE THREAD

**Issue by justinaustin** [Enet4/faiss-rs#1]
`remove_ids` is not a method of the `Index` trait, but it is implemented in FAISS. There is also a declaration of this method in `faiss-sys/src/bindings.rs` https://github.com/Enet4/faiss-rs/blob/master/faiss-sys/src/bindings.rs#L145. 

Was just wondering if there was a specific reason for this omission

**Comment by Enet4** [comment]
Thank you from reporting! That method might have slipped while I was working on the API, it should certainly be available on that trait.

Do you think you can propose a PR? I'm currently on a tight schedule, but I would be willing to provide a bit of guidance.
