### ISSUE TITLE
Add support IndexIVFFlat

### ISSUE THREAD

**Issue by ava57r** [Enet4/faiss-rs#13]
Hello.

faiss-sys supported IndexIVFFlat functions.

**Comment by ava57r** [comment]
We can't cast type of Index.
They are different types.

here https://github.com/Enet4/faiss-rs/blob/master/faiss-sys/src/bindings.rs#L702
`FaissIndexIVFFlat_H` != FaissIndex_H

for IndexIVF
https://github.com/Enet4/faiss-rs/blob/master/faiss-sys/src/bindings.rs#L756
It is equal.

It supports for IndexIVF only.
 https://github.com/facebookresearch/faiss/blob/master/c_api/IndexIVF_c.h#L39

**Comment by ava57r** [comment]
We can add fixes

from 
https://github.com/facebookresearch/faiss/pull/1764

to 
https://github.com/Enet4/faiss/tree/c_api_head

or we are waiting a new version faiss?

**Comment by Enet4** [comment]
Regarding the new version, it is mostly a matter of time until I finish reviewing #12 and #14, after which I will just release a new version of `faiss-rs` with the note that users should install a patched version of Faiss.

Until then, a PR to add this index type based on the current upstream would be welcome.

**Comment by ava57r** [comment]
I am speaking only https://github.com/Enet4/faiss/tree/c_api_head
I would like dev impl IVFFlat.
I going to use  fork https://github.com/Enet4/faiss/tree/c_api_head for local development.

**Comment by ava57r** [comment]
resolved by #17
