### ISSUE TITLE
Support faiss_index_gpu_to_cpu in GpuIndexImpl

### ISSUE THREAD

**Issue by ava57r** [Enet4/faiss-rs#37]
Now `GpuIndexImpl` supports only cpu -> gpu

Add support function `faiss_index_gpu_to_cpu`

**Comment by Enet4** [comment]
I'm not sure I follow. Don't [`GpuIndexImpl#to_cpu`](https://docs.rs/faiss/0.10.0/faiss/index/gpu/struct.GpuIndexImpl.html#method.to_cpu) and [`GpuIndexImpl#into_cpu`](https://docs.rs/faiss/0.10.0/faiss/index/gpu/struct.GpuIndexImpl.html#method.into_cpu) work for converting a GPU index back to a CPU index? [source](https://docs.rs/faiss/0.10.0/src/faiss/index/gpu.rs.html#209-215)

**Comment by ava57r** [comment]
Oh! I am sorry!
I did not see
