### ISSUE TITLE
Slow training IVF indexes

### ISSUE THREAD

**Issue by ava57r** [Enet4/faiss-rs#40]
I tried comparison two kinds of program `python` and `c_api` 

Both test lib use OpenBlas and LAPACK.

OS: Oracle Linux 8.3

## Python results

faiss lib from `anaconda` channel `conda-forge`

In python on GPU

```python
import numpy as np
import faiss

d = 128
res = faiss.StandardGpuResources()

index = faiss.index_factory(d, "IVF16384,Flat")
index.verbose = True
select_gpu = 0

xt = faiss.rand((1000000, d))
index_ivf = faiss.extract_index_ivf(index)
clustering_index = faiss.index_cpu_to_gpu(res, select_gpu, faiss.IndexFlatL2(d))
index_ivf.clustering_index = clustering_index

index.train(xt)

```

```console
time python3 train-gpu-rand.py 
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real    0m8.057s
user    1m59.744s
sys     0m17.446s
```

In python on CPU

```python
import numpy as np
import faiss

d = 128
index = faiss.index_factory(d, "IVF16834,Flat")
index.verbose = True

xt = faiss.rand((1000000, d))
index.train(xt)

```

```console
time python3 train-cpu-rand.py 
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real    7m13.904s
user    403m29.746s
sys     519m31.349s
```

## Rust bindings

in Rust on CPU
use faiss-rs` v0.10`

```rust 
use rand::prelude::*;
use faiss::Index;

fn main() {
    let d:usize = 128;
    let mut rng = rand::thread_rng();
    let mut xt:Vec<f32> = Vec::with_capacity(1_000_000 * d);
    for _ in 0..(1_000_000 * d) {
        xt.push(rng.gen());
    }

    let mut index = faiss::index_factory(
        d as u32,
        "IVF16834,Flat",
        faiss::MetricType::L2,
    )
    .unwrap();

    index.set_verbose(true);
    index.train(&xt).unwrap();
}

```

build from source faiss lib
https://github.com/facebookresearch/faiss/pull/1838
from branch `https://github.com/ava57r/faiss/tree/c_api_avx2` commit https://github.com/ava57r/faiss/commit/02ecc5be906fe787079054e236d2f58119c373e2

options 

```
cmake -B build \
-DBUILD_TESTING=OFF \
-DFAISS_ENABLE_GPU=OFF \
-DFAISS_OPT_LEVEL=avx2 \
-DFAISS_ENABLE_C_API=ON \
-DFAISS_ENABLE_PYTHON=OFF \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release .
make -C build -j
```

results 
I kill the process

first time

```console
   Compiling train-faiss-cpu v0.1.0 (/home/faiss-dev/train-faiss-cpu)
    Finished release [optimized] target(s) in 0.36s
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
^C

real    70m43.693s
user    1032m34.066s
sys     5m17.008s
```
second time 

```console
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
^C

real    16m37.219s
user    242m21.940s
sys     1m22.869s
```

I can't find a reason this behavior.

Could We need to add benckmark(s)?

**Comment by Enet4** [comment]
Could you please include how you are building and running the Rust application? It should be in release mode for a fair comparison.

The random vector data set generation can be a bit more idiomatic:

```rust
let xt: Vec<f32> = rng.sample_iter(rand::distributions::Standard)
    .take(1_000_000 * d)
    .collect();
```

Other than that, some profiling would help identify where the potential overhead is.

**Comment by ava57r** [comment]
Commands:

in `faiss` dir

```
cp build/c_api/libfaiss_c.so ~/faiss-lib/libfaiss_c.so
cp build/faiss/libfaiss.so ~/faiss-lib/libfaiss.so
cp build/faiss/libfaiss_avx2.so ~/faiss-lib/libfaiss_avx2.so
```

run training program

```
time LD_LIBRARY_PATH=/home/user/faiss-lib/ LIBRARY_PATH=/home/user/faiss-lib/ cargo run --release
```

**Comment by ava57r** [comment]
I tried IVF1024

python cpu

```console
time python3 train-cpu-rand.py 
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real    0m8.587s
user    8m26.756s
sys     10m56.531s
```

Rust

```console
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real    4m51.672s
user    68m31.671s
sys     1m9.906s
```
I tried `perf` util

![perf results IVF1024](https://user-images.githubusercontent.com/20382553/126179382-738a0fe3-0263-464f-8349-9603c91337e2.png)

**Comment by Enet4** [comment]
I tried to run the same Rust program in my environment (although I don't have a Python environment handy at the moment). 
Intel Core i7-9750H CPU, 12GB, running Manjaro Linux, kernel 5.12.9, with the index factory descriptor changed to `"IVF1024,Flat"`.

It does take a long time, but it appears to spend most of it in `sgemm_`.

![perf stat cargo run --release](https://user-images.githubusercontent.com/4738426/126373714-21b3c776-afbf-4515-8b8c-1f79a3ed6c01.png)

What is particularly curious is that it is not parallelizing the training process (should it?). In any case, the performance differences could either be related with the differences in the BLAS versions that were linked, or maybe how the Python bindings are set up for multithreading.

Can you check whether Python is using multiple threads? And whether the Python faiss package is linking against OpenBLAS or MKL ([this script seems to suggest the latter]( [this script](https://github.com/facebookresearch/faiss/blob/master/conda/faiss/build-lib.sh)))? I imagine that this could make a severe difference.

**Comment by ava57r** [comment]
> What is particularly curious is that it is not parallelizing the training process (should it?). In any case, the performance differences could either be related with the differences in the BLAS versions that were linked, or maybe how the Python bindings are set up for multithreading.

It looks strange. I have a lot of threads being created, but only a few(max 3) are 100% loaded.

> 
> Can you check whether Python is using multiple threads? And whether the Python faiss package is linking against OpenBLAS or MKL ([this script seems to suggest the latter]( [this script](https://github.com/facebookresearch/faiss/blob/master/conda/faiss/build-lib.sh)))? I imagine that this could make a severe difference.

I will try.

I use `minicoda` + https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#installing-from-conda-forge for test python

**Comment by Enet4** [comment]
OK, I managed to run the Python program with miniconda3 and the faiss-cpu package. It saturated all 6 cores (hyperthreading disabled) and ran pretty fast.

```none
❯ time /opt/miniconda3/bin/python main-cpu.py 
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real	0m7.115s
user	0m32.828s
sys	0m8.887s
```

The Rust version:

```none
❯ time cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.00s
     Running `target/release/use-faiss`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
        Training IVF residual
IndexIVF: no residual training

real    4m35.884s
user    4m38.034s
sys     0m0.293s
```

Although I am not entirely sure, both appear to be using OpenBLAS. Maybe some configuration is lacking. We could also remove some intermediate layers and write an equivalent C++ program.

**Comment by ava57r** [comment]
I tried C++

modied [`example_c`](https://github.com/facebookresearch/faiss/blob/master/c_api/example_c.c)

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "AutoTune_c.h"
#include "IndexFlat_c.h"
#include "Index_c.h"
#include "clone_index_c.h"
#include "error_c.h"
#include "index_factory_c.h"
#include "index_io_c.h"

#define FAISS_TRY(C)                                       \
    {                                                      \
        if (C) {                                           \
            fprintf(stderr, "%s", faiss_get_last_error()); \
            exit(-1);                                      \
        }                                                  \
    }

double drand() {
    return (double)rand() / (double)RAND_MAX;
}

int main() {
    time_t seed = time(NULL);
    srand(seed);
    printf("Generating some data...\n");
    int d = 128;     // dimension
    int nb = 1000000; // database size
    float* xb = malloc(d * nb * sizeof(float));

    for (int i = 0; i < nb; i++) {
        for (int j = 0; j < d; j++)
            xb[d * i + j] = drand();
        xb[d * i] += i / 1000.;
    }

    FaissIndex* index = NULL;
    FAISS_TRY(faiss_index_factory(
            &index, d, "IVF1024,Flat", METRIC_L2)); // use factory to create index
    printf("is_trained = %s\n",
           faiss_Index_is_trained(index) ? "true" : "false");
    
    FAISS_TRY(faiss_Index_train(index, nb, xb)); // add vectors to the index
    printf("ntotal = %lld\n", faiss_Index_ntotal(index));

    printf("Freeing index...\n");
    faiss_Index_free(index);
    printf("Done.\n");

    return 0;
}
```

results:

```console
time main_cpu 
Generating some data...
is_trained = false
ntotal = 0
Freeing index...
Done.

real	4m52.279s
user	71m50.702s
sys	1m37.375s
```

**Comment by ava57r** [comment]
in https://anaconda.org/conda-forge/faiss v1.7.0

**Comment by ava57r** [comment]
I had problems with slow training earlier but now I can reproduce it's. In v1.6.3

**Comment by ava57r** [comment]
> What is particularly curious is that it is not parallelizing the training process (should it?). In any case, the performance differences could either be related with the differences in the BLAS versions that were linked, or maybe how the Python bindings are set up for multithreading.
> 
> Can you check whether Python is using multiple threads? And whether the Python faiss package is linking against OpenBLAS or MKL ([this script seems to suggest the latter]( [this script](https://github.com/facebookresearch/faiss/blob/master/conda/faiss/build-lib.sh)))? I imagine that this could make a severe difference.

python uses
- multiple threads
- OpenBLAS from miniconda installation

**Comment by ava57r** [comment]
build options https://github.com/facebookresearch/faiss/issues/1511

OpenBLAS supports avx2 from v0.3.8 https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.8

test CentOS

```
rpm -qa | grep blas
blas-3.8.0-8.el8.x86_64

rpm -qa | grep lapack
lapack-3.8.0-8.el8.x86_64
```

miniconda3

```console
conda list | grep blas
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
```

https://github.com/xianyi/OpenBLAS/tree/v0.3.12

**Comment by ava57r** [comment]
in CentOS
I installed and rebuild libraries and binaries.

```console
sudo dnf install openblas
```

```console
rpm -qa | grep openblas
openblas-0.3.12-1.el8.x86_64
```

```console
ldd ./libfaiss_c.so 
	libfaiss_avx2.so
	libopenblas.so.0
```

Rust version OMP_WAIT_POLICY=PASSIVE

```console
time OMP_WAIT_POLICY=PASSIVE cargo run --release
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real	0m20.339s
user	0m47.973s
sys	0m26.781s
```

Rust version without OMP_WAIT_POLICY

```console 
time cargo run --release
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real	0m20.186s
user	0m45.038s
sys	0m20.870s
```

C++ version without OMP_WAIT_POLICY

```console
time main_cpu
Generating some data...
is_trained = false
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training
ntotal = 0
Freeing index...
Done.

real	0m20.714s
user	0m53.912s
sys	0m27.579s
```

**Comment by ava57r** [comment]
I tried again with MKL `BLA_VENDOR=Intel10_64_dyn`

python version. pytorch installation

```console
time python3 train-cpu-rand.py 
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real	0m11.389s
user	2m20.324s
sys	5m0.904s
```

Rust version with MKL

```console 
time LD_LIBRARY_PATH=/usr/local/lib64:/opt/intel/mkl/lib/intel64 cargo run --release 

    Finished release [optimized] target(s) in 0.01s
     Running `target/release/train-faiss-cpu`
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training

real	0m36.642s
user	18m36.431s
sys	0m18.177s

```

C++ with MKL

```console
time LD_LIBRARY_PATH=/usr/local/lib64:/opt/intel/mkl/lib/intel64 ./build/c_api/main_cpu 
Generating some data...
is_trained = false
Training level-1 quantizer
Training level-1 quantizer on 1000000 vectors in 128D
Training IVF residual
IndexIVF: no residual training
ntotal = 0
Freeing index...
Done.

real	0m37.687s
user	18m46.975s
sys	0m18.039s
```

It largely depends on how to configure the faiss libraries. It can be seen that the Rust code does not give an additional slowdown in this case
