### ISSUE TITLE
Faiss c_api dynamic library is called libfaiss_c.so not faiss_c

### ISSUE THREAD

**Issue by jdoig** [Enet4/faiss-rs#6]
I've just worked through the readme to get this to build and the output of `make`-ing faiss's `c_api` is called `libfaiss_c.so`.

Copying this to `/usr/lib` and changing `faiss-sys/Cargo.toml` allows me to build this project again.

Happy to put a PR in to fix this up, I just wanted to flag this up prior to that incase it was a mistake on my part in the setup.

**Comment by Enet4** [comment]
Sorry if the readme was not clear enough on this end. For what it's worth, this is already spelled out in the [root documentation](https://docs.rs/faiss/0.8.0/faiss/#preparing):

> This will result in the dynamic library faiss_c ("libfaiss_c.so" in Linux), which needs to be installed in a place where your system will pick up.

The `lib` prefix and is implicitly assumed on Linux systems. Should it eventually have Windows support, the file would have been named "faiss_c.dll".

With that said, a PR with a small change to clarify this in README.md would be welcomed.

**Comment by Enet4** [comment]
Closing as this appeared to be just a sporadic misunderstanding.
