### ISSUE TITLE
Can you also add support for static libraries?

### ISSUE THREAD

**Issue by web3creator** [Enet4/faiss-rs#68]
hello,Can you also add support for static libraries?

**Comment by Enet4** [comment]
Hello! There was an attempt at supporting static linking not long ago (#67). It was probably working for the most of it, but the original author seemingly gave up on it before I could get the time to review it. If someone is willing to commandeer the contribution, we can try bringing it upstream again.

**Comment by web3creator** [comment]
I referred to the implementation of  https://github.com/rust-rocksdb/rust-rocksdb, but there are many problems, I don't know C language, I am learning and hope to contribute to the system

**Comment by web3creator** [comment]
@SkyFan2002 of course

**Comment by Enet4** [comment]
Baseline support for static linking has just dropped with version 0.12.1 (#69 and #70). Extending this to support more options (e.g. `avx2` target) may be done in future releases.
