### ISSUE TITLE
`&mut self` argument on `index.search`

### ISSUE THREAD

**Issue by osmarks** [Enet4/faiss-rs#84]
`Index.search` [takes](https://docs.rs/faiss/latest/src/faiss/index/mod.rs.html#171) a `&mut self` argument. Is it safe to change this to `&self`? I had assumed that `.search` didn't mutate anything, and not being able to concurrently do searches is somewhat problematic for my application.

**Comment by osmarks** [comment]
I failed to notice `ConcurrentIndex`. Sorry.

**Comment by Enet4** [comment]
See also: https://github.com/Enet4/faiss-rs/issues/11
