### ISSUE TITLE
Support feature "Using multiple GPUs"

### ISSUE THREAD

**Issue by ava57r** [Enet4/faiss-rs#9]
Hello.
Are you planning to support the use of multiple graphics cards?

Faiss wiki [Using multiple GPUs](https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs#using-multiple-gpus)

**Comment by andreevlex** [comment]
Need to extend c_api?
https://github.com/facebookresearch/faiss/issues/1414

**Comment by ava57r** [comment]
Hello.
Is it https://github.com/Enet4/faiss-rs/tree/multi-gpu actual commits?

**Comment by Enet4** [comment]
@ava57r Oh, I might have pushed those commits to a separate branch, but I am not sure if the contribution was complete and ready for a pull request. I can try to get a time slot to check it out and further maintain the project, but in the meantime feel free to test and experiment with it if you can.

**Comment by ava57r** [comment]
I want to try to make support for this functionality
